# Generated by Django 5.0.6 on 2024-07-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mv_poledefects',
            name='pole_type',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE THE STATUS----'), ('10mwooden', '10m WOODEN'), ('11mwooden', '11m WOODEN'), ('12mwooden', '12m WOODEN'), ('10mconcrete', '10m CONCRETE'), ('11mconcrete', '11m CONCRETE'), ('12mconcrete', '12m CONCRETE'), ('14mconcrete', '14m CONCRETE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poledefects_maintenance',
            name='pole_type',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE THE STATUS----'), ('10mwooden', '10m WOODEN'), ('11mwooden', '11m WOODEN'), ('12mwooden', '12m WOODEN'), ('10mconcrete', '10m CONCRETE'), ('11mconcrete', '11m CONCRETE'), ('12mconcrete', '12m CONCRETE'), ('14mconcrete', '14m CONCRETE')], max_length=50, null=True),
        ),
    ]
