# Generated by Django 5.0.6 on 2024-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumv', '0002_alter_mv_poledefects_pole_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvinspection',
            name='aprv_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mvmaitenance',
            name='aprv_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poledefects_maintenance',
            name='aprv_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
