# Generated by Django 5.0.7 on 2024-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediumv', '0003_alter_mvinspection_aprv_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mv_poledefects',
            name='defect_type',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE THE STATUS----'), ('rotten', 'ROTTEN'), ('leaning', 'LEANING'), ('midspanpole', 'MIDSPAN POLE'), ('brockenpole', 'BROKEN POLE')], max_length=50, null=True),
        ),
    ]
