# Generated by Django 5.0.7 on 2024-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transdist', '0002_sixtysix_kv_customer_sixtysix_kv_substation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sixtysix_kv_meter',
            name='conn_config',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
