# Generated by Django 5.0.7 on 2024-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transdist', '0003_alter_sixtysix_kv_meter_conn_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sixtysix_kv_meter',
            name='meter_config',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('3P3W', '3P3W'), ('3P4W', '3P4W')], max_length=20, null=True),
        ),
    ]
