# Generated by Django 5.0.6 on 2024-07-16 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterno', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Meter Number')),
                ('accountno', models.IntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('totalbalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('last_bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('systemreading', models.IntegerField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.TextField(blank=True, max_length=300, null=True)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('itin', models.CharField(blank=True, max_length=300, null=True)),
                ('xcood', models.CharField(blank=True, max_length=300, null=True)),
                ('ycood', models.CharField(blank=True, max_length=300, null=True)),
                ('dt_asigned', models.DateField()),
                ('totalbalance_new', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('target_acc', models.BooleanField(default=True)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('asigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_asigned_by', to='user.userprofile')),
                ('asigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_asigned_to', to='user.userprofile')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_debt_list', to='main.county')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_debt_list', to='main.region')),
            ],
            options={
                'ordering': ['-dtadd'],
            },
        ),
        migrations.CreateModel(
            name='Revenuerecollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterno', models.CharField(blank=True, max_length=255, verbose_name='Meter Number')),
                ('accountno', models.IntegerField(blank=True, null=True)),
                ('collection_status', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('paid', 'PAID'), ('fdc', 'FDC'), ('disconnected', 'DISCONNECTED'), ('poledisconnection', 'POLE DISCONNECTION'), ('cablerecovery', 'CABLE RECOVERY'), ('notonsite', 'NOT-ON-SITE'), ('faulty', 'FAULTY'), ('wrongreading', 'WRONG READING')], default='pending', max_length=50)),
                ('reading', models.IntegerField(blank=True, null=True)),
                ('amountpaid', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('totalbalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('verified_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('incms_status', models.BooleanField(default=False)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('xcood', models.CharField(blank=True, max_length=300, null=True)),
                ('ycood', models.CharField(blank=True, max_length=300, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_revenue_resolved', to='main.county')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_rev_action', to='main.region')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_list', to='revenue.debtlist')),
            ],
            options={
                'ordering': ['-dtadd'],
            },
        ),
        migrations.AddIndex(
            model_name='debtlist',
            index=models.Index(fields=['meterno'], name='revenue_deb_meterno_0dbfd8_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuerecollection',
            index=models.Index(fields=['meterno'], name='revenue_rev_meterno_1c9b4a_idx'),
        ),
    ]
