# Generated by Django 5.0.7 on 2024-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtlist',
            name='meterno',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meter Number'),
        ),
    ]
