# Generated by Django 5.0.7 on 2024-08-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_alter_debtlist_meterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtlist',
            name='accountno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
