# Generated by Django 5.0.6 on 2024-05-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.account'),
        ),
        migrations.AddField(
            model_name='da',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_da', to='main.county'),
        ),
        migrations.AddField(
            model_name='da',
            name='dae',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dae_user', to='user.account'),
        ),
        migrations.AddField(
            model_name='da',
            name='logged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_user_da', to='user.account'),
        ),
        migrations.AddField(
            model_name='department',
            name='div',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.divisions'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeder_county', to='main.county'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='da',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeder_da', to='main.da'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='logged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_user_county', to='user.account'),
        ),
        migrations.AddField(
            model_name='feeder_sections',
            name='feeder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_feeder', to='main.feeder'),
        ),
        migrations.AddField(
            model_name='feeder_sections',
            name='logged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_feeder_logged', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='meters',
            name='asigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Meters_asigned', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='meters',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.county'),
        ),
        migrations.AddField(
            model_name='meters',
            name='resposnsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Meters_responsible', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='meters',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Meters_user', to='user.account'),
        ),
        migrations.AddField(
            model_name='region',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.account'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeder_region', to='main.region'),
        ),
        migrations.AddField(
            model_name='da',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_da', to='main.region'),
        ),
        migrations.AddField(
            model_name='county',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.region'),
        ),
        migrations.AddField(
            model_name='sector',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_sectors', to='main.county'),
        ),
        migrations.AddField(
            model_name='sector',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.account'),
        ),
        migrations.AddField(
            model_name='meters',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sector'),
        ),
        migrations.AddIndex(
            model_name='meters',
            index=models.Index(fields=['dtadd'], name='main_meters_dtadd_90c720_idx'),
        ),
    ]
