# Generated by Django 5.0.7 on 2025-01-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='retrofit_daily_target',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='retrofit_target',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='retrofit_daily_target',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='retrofit_target',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
