# Generated by Django 5.0.7 on 2025-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_county_retrofit_daily_target_county_retrofit_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='publiclighting_daily_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='publiclighting_target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
