# Generated by Django 5.0.7 on 2025-10-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_region_publiclighting_daily_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder_sections',
            name='aprx_length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Aproximate length in km"s', max_digits=4),
        ),
    ]
