# Generated by Django 5.0.6 on 2024-07-16 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.CharField(max_length=100, unique=True, verbose_name='Tag Number')),
                ('inv_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inventory Name')),
                ('office_station', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('good', 'GOOD'), ('faulty', 'FAULTY')], max_length=100, null=True, verbose_name='Condition')),
                ('dt_purchase', models.DateField()),
                ('purchase_price_vat_incl', models.FloatField()),
                ('purchase_price_vat_excl', models.FloatField()),
                ('reciepient_stid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Receipeint Staff Number')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inventory Description')),
                ('quantity', models.IntegerField(default=0)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier Name')),
                ('lpo_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='LPO Number')),
                ('ac_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Number')),
                ('internal_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='Internal Order')),
                ('minute_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Minute Number')),
                ('lon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('lat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.county', verbose_name='County')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.department', verbose_name='Inventory department')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspector_staff', to='user.userprofile')),
                ('inv_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hradmin.inventory_group', verbose_name='Inventory Group')),
            ],
        ),
    ]
