# Generated by Django 5.0.7 on 2024-09-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lvinspection',
            old_name='kvarating',
            new_name='kvaratingg',
        ),
        migrations.RenameField(
            model_name='maintainlvinspection',
            old_name='kvarating',
            new_name='kvaratingg',
        ),
    ]
