# Generated by Django 5.0.7 on 2024-09-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lv', '0002_rename_kvarating_lvinspection_kvaratingg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lvinspection',
            old_name='kvaratingg',
            new_name='kvarating',
        ),
        migrations.RenameField(
            model_name='maintainlvinspection',
            old_name='kvaratingg',
            new_name='kvarating',
        ),
    ]
