# Generated by Django 5.0.7 on 2024-10-29 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv', '0003_rename_kvaratingg_lvinspection_kvarating_and_more'),
        ('main', '0002_initial'),
        ('user', '0002_alter_userprofile_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadChecks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_voltage', models.CharField(blank=True, choices=[('', '----CHOOSE THE TYPE----'), ('33', '33'), ('11', '11')], max_length=10, null=True)),
                ('tx_rating', models.CharField(blank=True, choices=[('', '----CHOOSE THE STATUS----'), ('5', '5'), ('15', '15'), ('25', '25'), ('50', '50'), ('100', '100'), ('200', '200'), ('315', '315'), ('630', '630'), ('1000', '1000'), ('3*5', '3*5'), ('3*15', '3*15'), ('3*25', '3*25')], max_length=20, null=True)),
                ('number_of_circuits', models.IntegerField(blank=True, null=True)),
                ('voltage_ll_ry', models.CharField(blank=True, max_length=10, null=True)),
                ('voltage_ll_yb', models.CharField(blank=True, max_length=10, null=True)),
                ('voltage_ll_br', models.CharField(blank=True, max_length=10, null=True)),
                ('voltage_ln_rn', models.CharField(blank=True, max_length=10, null=True)),
                ('voltage_ln_yn', models.CharField(blank=True, max_length=10, null=True)),
                ('voltage_ln_bn', models.CharField(blank=True, max_length=10, null=True)),
                ('phase_loads_r', models.CharField(blank=True, max_length=10, null=True)),
                ('phase_loads_y', models.CharField(blank=True, max_length=10, null=True)),
                ('phase_loads_b', models.CharField(blank=True, max_length=10, null=True)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_loadchecks', to='main.county')),
                ('inspectedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspectedby_loadchecks', to='user.userprofile')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_loadchecks', to='main.region')),
                ('substation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substation_loadchecks', to='lv.substation')),
            ],
        ),
    ]
