# Generated by Django 5.0.7 on 2024-10-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv', '0004_loadchecks'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadchecks',
            name='aprv_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='save_status',
            field=models.BooleanField(default=False),
        ),
    ]
