# Generated by Django 5.0.7 on 2024-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv', '0005_loadchecks_aprv_status_loadchecks_save_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_b_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_b_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_b_4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_b_5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_r_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_r_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_r_4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_r_5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_y_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_y_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_y_4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loadchecks',
            name='phase_loads_y_5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
