# Generated by Django 5.0.7 on 2025-04-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv', '0006_loadchecks_phase_loads_b_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='txfailure',
            name='txweight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
