# Generated by Django 5.0.7 on 2025-04-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lv', '0007_txfailure_txweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lvinspection',
            name='kvarating',
        ),
    ]
