# Generated by Django 5.0.7 on 2025-04-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv', '0008_remove_lvinspection_kvarating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lvinspection',
            name='kvarating',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE THE STATUS----'), ('5', '5'), ('15', '15'), ('25', '25'), ('50', '50'), ('100', '100'), ('200', '200'), ('315', '315'), ('630', '630'), ('1000', '1000'), ('3*5', '3*5'), ('3*15', '3*15'), ('3*25', '3*25')], max_length=50, null=True),
        ),
    ]
