# Generated by Django 5.0.7 on 2025-04-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv', '0009_lvinspection_kvarating'),
    ]

    operations = [
        migrations.AddField(
            model_name='substationinspection',
            name='txweight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
