# Generated by Django 5.0.7 on 2025-10-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lv', '0010_substationinspection_txweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainlvinspection',
            name='other_defects',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE THE STATUS----'), ('yes', 'YES'), ('no', 'NO')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='substationmaintenance',
            name='other_defects',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE THE STATUS----'), ('yes', 'YES'), ('no', 'NO')], max_length=50, null=True),
        ),
    ]
