# Generated by Django 5.0.6 on 2024-05-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('stid', models.IntegerField(db_index=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-stid'],
                'indexes': [models.Index(fields=['stid'], name='user_accoun_stid_19fc77_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profiletype', models.CharField(choices=[('cse', 'CSE'), ('input', 'INPUT'), ('other', 'OTHER')], default='other', max_length=6)),
                ('campaign', models.CharField(choices=[('zerobills', 'ZERO BILLS CAMPAIGN'), ('revenue', 'REVENUE COLLECTION'), ('dc', 'DOMESTIC CUSTOMERS'), ('threephase', 'HIGH END ACCOUNTS'), ('telcos', 'TELCOS INSPECTION'), ('publiclighting', 'PUBLIC LIGHTING'), ('lp', 'LARGE POWER'), ('network_technician', 'NETWORK TECHNICIAN'), ('network_supervisors', 'NETWORK SUPERVISORS'), ('other', 'OTHER'), ('transdist', 'TRANSMISSION & PRIMARY SUBSTATIONS'), ('contractor_allandick', 'CONTRACTOR'), ('hradmin', 'HRADMIN')], default='other', max_length=20)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.county')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
            ],
            options={
                'ordering': ['-user'],
                'indexes': [models.Index(fields=['user'], name='user_userpr_user_id_d39789_idx')],
            },
        ),
    ]
