# Generated by Django 5.0.7 on 2024-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='campaign',
            field=models.CharField(choices=[('zerobills', 'ZERO BILLS CAMPAIGN'), ('revenue', 'REVENUE COLLECTION'), ('dc', 'DOMESTIC CUSTOMERS'), ('threephase', 'HIGH END ACCOUNTS'), ('telcos', 'TELCOS INSPECTION'), ('publiclighting', 'PUBLIC LIGHTING'), ('elsewedy_replacement', 'ELSEWEDY REPLACEMENTS'), ('lp', 'LARGE POWER'), ('network_technician', 'NETWORK TECHNICIAN'), ('network_supervisors', 'NETWORK SUPERVISORS'), ('other', 'OTHER'), ('transdist', 'TRANSMISSION & PRIMARY SUBSTATIONS'), ('contractor_allandick', 'CONTRACTOR'), ('hradmin', 'HRADMIN')], default='other', max_length=20),
        ),
    ]
