# Generated by Django 5.0.7 on 2024-08-20 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('postpaid', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Largepower_accounts_2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number')),
                ('srn', models.CharField(blank=True, max_length=100, null=True, verbose_name='SRN')),
                ('meterno', models.CharField(blank=True, max_length=100, null=True, verbose_name='MEter Number')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('inspection_status', models.IntegerField(default=0)),
                ('asigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.county')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region')),
            ],
        ),
    ]
