# Generated by Django 5.0.7 on 2024-08-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('postpaid', '0002_largepower_accounts_2024'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lp_typeofindustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('asigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='lp_inspect_customerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterno', models.CharField(blank=True, max_length=100, null=True)),
                ('srn', models.CharField(blank=True, max_length=100, null=True)),
                ('accountno', models.CharField(blank=True, max_length=100, null=True)),
                ('smart_meter_i', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('POLEMOUNTED', 'POLE MOUNTED'), ('GROUNDMOUNTED', ' GROUND MOUNTED')], max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('save_status', models.BooleanField(default=False)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lp_customerdata_county', to='main.county')),
                ('inspectedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
                ('lp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_customerdata', to='postpaid.largepower_accounts_2024')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lp_customerdata_region', to='main.region')),
                ('type_of_industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='industry_type', to='postpaid.lp_typeofindustry')),
            ],
        ),
    ]
