# Generated by Django 5.0.7 on 2024-08-20 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('postpaid', '0003_lp_typeofindustry_lp_inspect_customerdata'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lp_inspect_customerdata',
            name='county',
        ),
        migrations.RemoveField(
            model_name='lp_inspect_customerdata',
            name='region',
        ),
        migrations.RemoveField(
            model_name='lp_inspect_customerdata',
            name='save_status',
        ),
        migrations.CreateModel(
            name='lp_new_inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('save_status', models.BooleanField(default=False)),
                ('over_rem', models.TextField(blank=True, null=True)),
                ('declaration', models.BooleanField(default=False)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lp_new_inspection_county', to='main.county')),
                ('inspectedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
                ('lp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_new_inspection', to='postpaid.largepower_accounts_2024')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lp_new_inspection_region', to='main.region')),
            ],
        ),
        migrations.AlterField(
            model_name='lp_inspect_customerdata',
            name='lp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_customerdata', to='postpaid.lp_new_inspection'),
        ),
    ]
