# Generated by Django 5.0.7 on 2024-08-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0004_remove_lp_inspect_customerdata_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='ctvt_data',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='customer_data',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='meter_rading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='sealing_data',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='zera_test',
            field=models.IntegerField(default=0),
        ),
    ]
