# Generated by Django 5.0.7 on 2024-08-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0005_largepower_accounts_2024_ctvt_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='over_per',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
