# Generated by Django 5.0.7 on 2024-08-20 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0006_largepower_accounts_2024_over_per'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LP_inspection_sealing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prg_seal_init', models.CharField(blank=True, max_length=100, null=True)),
                ('prg_seal_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('term_sl_init', models.CharField(blank=True, max_length=100, null=True)),
                ('term_sl_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('testb_sl_init', models.CharField(blank=True, max_length=100, null=True)),
                ('testb_sl_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('body_sl_init', models.CharField(blank=True, max_length=100, null=True)),
                ('body_sl_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('smart_meter_sl_init', models.CharField(blank=True, max_length=100, null=True)),
                ('smart_meter_sl_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('amr_sl_init', models.CharField(blank=True, max_length=100, null=True)),
                ('amr_sl_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('other_sl_init', models.CharField(blank=True, max_length=100, null=True)),
                ('other_sl_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('inspectedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
                ('lp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_sealing', to='postpaid.lp_new_inspection')),
            ],
        ),
    ]
