# Generated by Django 5.0.7 on 2024-08-20 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0007_lp_inspection_sealing'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lp_inspect_ctvt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_config', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('3P3W', '3P3W'), ('3P4W', '3P4W')], max_length=20, null=True)),
                ('meter_voltage', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('1/1', '1/1'), ('11000/110', '11000/110'), ('132000/100', '132000/100'), ('132000/110', '132000/110'), ('220000/110', '220000/110'), ('33000/110', '33000/110'), ('66000/110', '66000/110')], max_length=20, null=True)),
                ('ct_ratio_prmed', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('1/1', '1/1'), ('100/1', '100/1'), ('100/5', '100/5'), ('1000/5', '1000/5'), ('1200/5', '1200/5'), ('150/1', '150/1'), ('150/5', '150/5'), ('1500/5', '1500/5'), ('200/1', '200/1'), ('200/5', '200/5'), ('2000/5', '2000/5'), ('25/1', '25/1'), ('250/5', '250/5'), ('30/1', '30/1'), ('300/1', '300/1'), ('300/5', '300/5'), ('360/1', '360/1'), ('40/5', '40/5'), ('400/1', '400/1'), ('400/5', '400/5'), ('50/1', '50/1'), ('50/5', '50/5'), ('500/5', '500/5'), ('800/1', '800/1'), ('800/5', '800/5')], max_length=20, null=True)),
                ('ctratio_img', models.ImageField(default='images/default.jpg', upload_to='images/lp2024/ctratio/%Y/%m/%d/')),
                ('ct_ratio_inst', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('1/1', '1/1'), ('100/1', '100/1'), ('100/5', '100/5'), ('1000/5', '1000/5'), ('1200/5', '1200/5'), ('150/1', '150/1'), ('150/5', '150/5'), ('1500/5', '1500/5'), ('200/1', '200/1'), ('200/5', '200/5'), ('2000/5', '2000/5'), ('25/1', '25/1'), ('250/5', '250/5'), ('30/1', '30/1'), ('300/1', '300/1'), ('300/5', '300/5'), ('360/1', '360/1'), ('40/5', '40/5'), ('400/1', '400/1'), ('400/5', '400/5'), ('50/1', '50/1'), ('50/5', '50/5'), ('500/5', '500/5'), ('800/1', '800/1'), ('800/5', '800/5')], max_length=20, null=True)),
                ('vt_ratio_prmed', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('1/1', '1/1'), ('11000/110', '11000/110'), ('132000/100', '132000/100'), ('132000/110', '132000/110'), ('220000/110', '220000/110'), ('33000/110', '33000/110'), ('66000/110', '66000/110')], max_length=20, null=True)),
                ('amr_recovered', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True)),
                ('ctvt_match', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True)),
                ('ctvt_mismatch_text', models.TextField(blank=True, null=True)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('inspectedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
                ('lp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_ctvt', to='postpaid.lp_new_inspection')),
            ],
        ),
    ]
