# Generated by Django 5.0.7 on 2024-08-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0008_lp_inspect_ctvt'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lp_inspect_zeratest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeratest', models.BooleanField(default=False)),
                ('error_trial', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('error_test_rem', models.TextField(blank=True, null=True)),
                ('register_error', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('register_error_rem', models.TextField(blank=True, null=True)),
                ('meter_passed', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('inspectedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
                ('lp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_zeratest', to='postpaid.lp_new_inspection')),
            ],
        ),
    ]
