# Generated by Django 5.0.7 on 2024-08-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0009_lp_inspect_zeratest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lp_inspect_zeratest',
            name='zeratest',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
