# Generated by Django 5.0.7 on 2024-08-21 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0010_alter_lp_inspect_zeratest_zeratest'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='current',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Lp_inspect_current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rphase_amcoder', models.CharField(blank=True, max_length=255, null=True)),
                ('rphase_meter', models.CharField(blank=True, max_length=255, null=True)),
                ('yphase_amcoder', models.CharField(blank=True, max_length=255, null=True)),
                ('yphase_meter', models.CharField(blank=True, max_length=255, null=True)),
                ('bphase_amcoder', models.CharField(blank=True, max_length=255, null=True)),
                ('bphase_meter', models.CharField(blank=True, max_length=255, null=True)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('load_balancing', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True)),
                ('currents_range', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True)),
                ('inspectedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
                ('lp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_current', to='postpaid.lp_new_inspection')),
            ],
        ),
    ]
