# Generated by Django 5.0.7 on 2024-08-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0011_largepower_accounts_2024_current_lp_inspect_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lp_inspect_current',
            name='load_balancing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
