# Generated by Django 5.0.7 on 2024-08-21 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0012_alter_lp_inspect_current_load_balancing'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LP_meter_readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_time_actual', models.TimeField(blank=True, null=True)),
                ('meter_time_meter', models.TimeField(blank=True, null=True)),
                ('meter_date_actual', models.DateField(blank=True, null=True)),
                ('meter_date_meter', models.DateField(blank=True, null=True)),
                ('kwh_180_cur', models.CharField(blank=True, max_length=255, null=True)),
                ('kwh_180_mem', models.CharField(blank=True, max_length=255, null=True)),
                ('reading_180_img', models.ImageField(default='images/default.jpg', upload_to='images/lp2024/reading180/%Y/%m/%d/')),
                ('reading_280_img', models.ImageField(default='images/default.jpg', upload_to='images/lp2024/reading280/%Y/%m/%d/')),
                ('kwh_280_cur', models.CharField(blank=True, max_length=255, null=True)),
                ('kwh_280_mem', models.CharField(blank=True, max_length=255, null=True)),
                ('kva_960_cur', models.CharField(blank=True, max_length=255, null=True)),
                ('kva_960_mem', models.CharField(blank=True, max_length=255, null=True)),
                ('kwh_181_cur', models.CharField(blank=True, max_length=255, null=True)),
                ('kwh_181_mem', models.CharField(blank=True, max_length=255, null=True)),
                ('kwh_182_cur', models.CharField(blank=True, max_length=255, null=True)),
                ('kwh_182_mem', models.CharField(blank=True, max_length=255, null=True)),
                ('kwh_150_cur', models.CharField(blank=True, max_length=255, null=True)),
                ('kwh_150_mem', models.CharField(blank=True, max_length=255, null=True)),
                ('r_phase_v', models.CharField(blank=True, max_length=255, null=True)),
                ('y_phase_v', models.CharField(blank=True, max_length=255, null=True)),
                ('b_phase_v', models.CharField(blank=True, max_length=255, null=True)),
                ('r_phase_c', models.CharField(blank=True, max_length=255, null=True)),
                ('y_phase_c', models.CharField(blank=True, max_length=255, null=True)),
                ('b_phase_c', models.CharField(blank=True, max_length=255, null=True)),
                ('pw_f', models.CharField(blank=True, max_length=255, null=True)),
                ('m_remarks', models.TextField(blank=True, null=True)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('inspectedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
                ('lp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_mreadings', to='postpaid.lp_new_inspection')),
            ],
        ),
    ]
