# Generated by Django 5.0.7 on 2024-08-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0013_lp_meter_readings'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lp_inspect_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_installed', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True)),
                ('solar_size', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_installation', models.DateField(blank=True, null=True)),
                ('overal_rem', models.TextField(blank=True, null=True)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('inspectedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
                ('lp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_solar', to='postpaid.lp_new_inspection')),
            ],
        ),
    ]
