# Generated by Django 5.0.7 on 2024-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0014_lp_inspect_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='otherinfo',
            field=models.IntegerField(default=0),
        ),
    ]
