# Generated by Django 5.0.7 on 2024-08-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0015_largepower_accounts_2024_otherinfo'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lp_inspect_ctvt',
            name='inspectedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='lp_inspect_ctvt',
            name='lp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lp_ctvt', to='postpaid.lp_new_inspection'),
        ),
        migrations.AlterField(
            model_name='lp_inspect_current',
            name='inspectedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='lp_inspect_current',
            name='lp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lp_current', to='postpaid.lp_new_inspection'),
        ),
        migrations.AlterField(
            model_name='lp_inspect_customerdata',
            name='inspectedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='lp_inspect_customerdata',
            name='lp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lp_customerdata', to='postpaid.lp_new_inspection'),
        ),
        migrations.AlterField(
            model_name='lp_inspect_info',
            name='inspectedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='lp_inspect_info',
            name='lp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lp_solar', to='postpaid.lp_new_inspection'),
        ),
        migrations.AlterField(
            model_name='lp_inspect_zeratest',
            name='inspectedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='lp_inspect_zeratest',
            name='lp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lp_zeratest', to='postpaid.lp_new_inspection'),
        ),
        migrations.AlterField(
            model_name='lp_inspection_sealing',
            name='inspectedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='lp_inspection_sealing',
            name='lp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lp_sealing', to='postpaid.lp_new_inspection'),
        ),
        migrations.AlterField(
            model_name='lp_meter_readings',
            name='inspectedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='lp_meter_readings',
            name='lp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lp_mreadings', to='postpaid.lp_new_inspection'),
        ),
    ]
