# Generated by Django 5.0.7 on 2024-08-22 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0016_alter_lp_inspect_ctvt_inspectedby_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='ctvt_mismatch',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='currents_mismatch',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='zera_failed',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lp_new_inspection',
            name='inspectedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lp_new_inspected_by', to='user.userprofile'),
        ),
    ]
