# Generated by Django 5.0.7 on 2024-09-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0017_largepower_accounts_2024_ctvt_mismatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lp_meter_readings',
            name='kva_970_cur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lp_meter_readings',
            name='kva_970_mem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lp_meter_readings',
            name='kwh_170_cur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lp_meter_readings',
            name='kwh_170_mem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_customerdata',
            name='smart_meter_i',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('POLEMOUNTEDACCESSIBLE', 'POLE MOUNTED ACCESSIBLE'), ('POLEMOUNTEDELEVATED', 'POLE MOUNTED ELEVATED'), ('GROUNDMOUNTEDACCESSIBLE', ' GROUND MOUNTED ACCESSIBLE'), ('GROUNDMOUNTEDELEVATED', ' GROUND MOUNTED ELEVATED')], max_length=100, null=True),
        ),
    ]
