# Generated by Django 5.0.7 on 2024-09-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('postpaid', '0019_elsewedyaccounts'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elsewedyaccounts',
            name='billed_reading',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ElsewedyReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Number')),
                ('oldmeter', models.CharField(max_length=100, unique=True, verbose_name='Meter Number Removed')),
                ('newmeter', models.CharField(max_length=100, unique=True, verbose_name='Meter Number Installed')),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('meteringstatus', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('okay', 'OKAY'), ('faulty', 'FAULTY'), ('tampered', 'TAMPERED'), ('bypassed', 'BYPASSED')], max_length=50, verbose_name='Metering Status')),
                ('faultystatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('blankscreen', 'BLANK SCREEN'), ('noncommunicating', 'NON COMMUNICATING'), ('obsolete', 'OBSOLETE'), ('fadeddigits', 'FADED DIGITS'), ('notpulsing', 'NOT PULSING'), ('burnt', 'BURNT'), ('batterylow', 'BATTERY LOW'), ('cuifaulty', 'CIU FAULTY'), ('notabletoloadtoken', 'NOT ABLE TO LOAD TOKEN'), ('looseglass', 'LOOSE GLASS')], default='NULL', max_length=50, null=True, verbose_name='Faulty Status')),
                ('tamperedstatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('brokenseaals', 'BROKEN SEALS'), ('disabledvoltage', 'DISABLED VOLTAGE'), ('disabledcurrent', 'DISABLED CURRENT'), ('brokenglass', 'BROKEN GLASS'), ('droppedlink', 'DROPPED LINK'), ('damagedmeter', 'DAMAGED METER'), ('foreignobjects', 'FOREIGN OBJECTS INTRODUCED')], max_length=50, null=True, verbose_name='Tampered Status')),
                ('bypassstatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('puncturedcable', 'PUNCTURED CABLE'), ('drilledcutout', 'DRILLED CUTOUT')], max_length=50, null=True, verbose_name='Bypass Status')),
                ('removal_reading', models.IntegerField(help_text='Required', verbose_name='Meter Removal Reading(This is a required Field)')),
                ('removal_img', models.ImageField(upload_to='images/elsewedy/removal/%Y/%m/%d/', verbose_name='CLEAR IMAGE OF REMOVED METER(This is Required)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Any Comment')),
                ('y', models.CharField(max_length=255, verbose_name='Y')),
                ('x', models.CharField(max_length=255, verbose_name='X')),
                ('validated', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('yes', 'YES'), ('no', 'NO')], max_length=50, verbose_name='Validated Status')),
                ('validate_status', models.BooleanField(default=False)),
                ('billed', models.BigIntegerField(default=0, verbose_name='Rebilled Amount')),
                ('consumption', models.IntegerField(default=0, verbose_name='Usage')),
                ('units', models.IntegerField(blank=True, null=True, verbose_name='Units')),
                ('seal_cover', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seal')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_elsewedy_repalcement', to='main.county')),
                ('elsewedy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elsewedy_replaced_meter', to='postpaid.elsewedyaccounts')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elsewedy_inspector', to='user.userprofile')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_elsewedy_repalcement', to='main.region')),
            ],
        ),
    ]
