# Generated by Django 5.0.7 on 2024-09-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0020_elsewedyaccounts_billed_reading_elsewedyreplacement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elsewedyaccounts',
            old_name='latitude',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='elsewedyaccounts',
            old_name='longitute',
            new_name='y',
        ),
    ]
