# Generated by Django 5.0.7 on 2024-09-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0021_rename_latitude_elsewedyaccounts_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elsewedyaccounts',
            name='diffunits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
