# Generated by Django 5.0.7 on 2024-09-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0022_elsewedyaccounts_diffunits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elsewedyreplacement',
            name='x',
        ),
        migrations.RemoveField(
            model_name='elsewedyreplacement',
            name='y',
        ),
    ]
