# Generated by Django 5.0.7 on 2024-09-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0024_domestic_customers_rri'),
    ]

    operations = [
        migrations.AddField(
            model_name='largepower_accounts_2024',
            name='final_sub',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lp_inspect_ctvt',
            name='amr_recovered',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO'), ('NOTAPPLICABLE', 'NOT APPLICABLE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_ctvt',
            name='ctvt_match',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO'), ('NOTAPPLICABLE', 'NOT APPLICABLE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_current',
            name='currents_range',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO'), ('NOTAPPLICABLE', 'NOT APPLICABLE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_info',
            name='solar_installed',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO'), ('NOTAPPLICABLE', 'NOT APPLICABLE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_zeratest',
            name='meter_passed',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO'), ('NOTAPPLICABLE', 'NOT APPLICABLE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_zeratest',
            name='zeratest',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO'), ('NOTAPPLICABLE', 'NOT APPLICABLE')], max_length=20, null=True),
        ),
    ]
