# Generated by Django 5.0.7 on 2024-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0025_largepower_accounts_2024_final_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lp_inspect_zeratest',
            name='meter_passed',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO'), ('NOTAPPLICABLE', 'NOT APPLICABLE')], max_length=20, null=True),
        ),
    ]
