# Generated by Django 5.0.7 on 2024-10-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0026_alter_lp_inspect_zeratest_meter_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lp_inspection_sealing',
            name='is_amr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lp_inspect_customerdata',
            name='smart_meter_i',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('POLEMOUNTEDACCESSIBLE', 'POLE MOUNTED ACCESSIBLE'), ('POLEMOUNTEDELEVATED', 'POLE MOUNTED ELEVATED'), ('GROUNDMOUNTEDACCESSIBLE', ' GROUND MOUNTED ACCESSIBLE'), ('GROUNDMOUNTEDELEVATED', ' GROUND MOUNTED ELEVATED'), ('AMR METERING', 'AMR METERING')], max_length=100, null=True),
        ),
    ]
