# Generated by Django 5.0.7 on 2024-10-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0027_lp_inspection_sealing_is_amr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lp_inspect_ctvt',
            name='amr_recovered',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_ctvt',
            name='ctvt_match',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_current',
            name='currents_range',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_customerdata',
            name='smart_meter_i',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('POLEMOUNTEDACCESSIBLE', 'POLE MOUNTED ACCESSIBLE'), ('POLEMOUNTEDELEVATED', 'POLE MOUNTED ELEVATED'), ('GROUNDMOUNTEDACCESSIBLE', ' GROUND MOUNTED ACCESSIBLE'), ('GROUNDMOUNTEDELEVATED', ' GROUND MOUNTED ELEVATED'), ('AMRMETERING', 'AMR METERING')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_info',
            name='solar_installed',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_zeratest',
            name='meter_passed',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspect_zeratest',
            name='zeratest',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspection_sealing',
            name='is_amr',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
