# Generated by Django 5.0.7 on 2024-10-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0028_alter_lp_inspect_ctvt_amr_recovered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lp_new_inspection',
            name='meterno',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Meter Number'),
        ),
    ]
