# Generated by Django 5.0.7 on 2024-11-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0029_lp_new_inspection_meterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lp_inspection_sealing',
            name='amr_sl_init',
            field=models.CharField(blank=True, help_text='Initail and Final cannot be the same', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspection_sealing',
            name='smart_meter_sl_init',
            field=models.CharField(blank=True, help_text='Initail and Final cannot be the same', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lp_inspection_sealing',
            name='term_sl_init',
            field=models.CharField(blank=True, help_text='Initail and Final cannot be the same', max_length=100, null=True),
        ),
    ]
