# Generated by Django 5.0.7 on 2025-01-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('postpaid', '0030_alter_lp_inspection_sealing_amr_sl_init_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrofitAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterno', models.CharField(max_length=20, unique=True, verbose_name='Meter Number')),
                ('accountno', models.CharField(max_length=20, verbose_name='Account Number')),
                ('itin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Itinerary')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector')),
                ('zone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Name')),
                ('cod_tarrif', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarrif')),
                ('supply_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supply Address')),
                ('y', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('x', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('status', models.BooleanField(default=False)),
                ('contract_type', models.CharField(blank=True, max_length=20, null=True)),
                ('tech_center', models.CharField(blank=True, max_length=255, null=True)),
                ('billed_reading', models.IntegerField(default=0)),
                ('incms_status', models.BooleanField(default=False)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('diffunits', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.county')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region')),
            ],
        ),
    ]
