# Generated by Django 5.0.7 on 2025-01-09 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_county_retrofit_daily_target_county_retrofit_target_and_more'),
        ('postpaid', '0031_retrofitaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrofitaccounts',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrofits_county', to='main.county'),
        ),
        migrations.AlterField(
            model_name='retrofitaccounts',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrofits_region', to='main.region'),
        ),
    ]
