# Generated by Django 5.0.7 on 2025-03-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0032_alter_retrofitaccounts_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_lighting_target',
            name='x',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='X'),
        ),
        migrations.AddField(
            model_name='public_lighting_target',
            name='y',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Y'),
        ),
    ]
