# Generated by Django 5.0.7 on 2025-03-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0033_public_lighting_target_x_public_lighting_target_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_lighting_inspection',
            name='meter_readable',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('yes', 'YES'), ('no', 'NO')], max_length=50, null=True, verbose_name='Meter Readable'),
        ),
        migrations.AddField(
            model_name='public_lighting_inspection',
            name='meter_type',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE A METER TYPE----'), ('nonsmart', 'NON SMART'), ('smart', 'SMART')], max_length=50, null=True, verbose_name='Meter Type'),
        ),
    ]
