# Generated by Django 5.0.7 on 2025-03-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0034_public_lighting_inspection_meter_readable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_lighting_inspection',
            name='meter_type',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE A METER TYPE----'), ('nonsmart', 'NON SMART'), ('smart', 'SMART')], max_length=50, null=True, verbose_name='Meter Installation Type'),
        ),
        migrations.AlterField(
            model_name='public_lighting_inspection',
            name='reading',
            field=models.IntegerField(default=0, help_text='Required', verbose_name='Meter Reading(This is a required Field)'),
        ),
    ]
