# Generated by Django 5.0.7 on 2025-03-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0035_alter_public_lighting_inspection_meter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_lighting_inspection',
            name='reading',
            field=models.IntegerField(blank=True, help_text='Required', null=True, verbose_name='Meter Reading(This is a required Field)'),
        ),
    ]
