# Generated by Django 5.0.7 on 2025-03-20 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_county_retrofit_daily_target_county_retrofit_target_and_more'),
        ('postpaid', '0036_alter_public_lighting_inspection_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_lighting_inspection',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_public_lighting', to='main.region'),
        ),
        migrations.AlterField(
            model_name='public_lighting_inspection',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_public_lighting', to='main.county'),
        ),
    ]
