# Generated by Django 5.0.7 on 2025-03-20 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_county_retrofit_daily_target_county_retrofit_target_and_more'),
        ('postpaid', '0037_public_lighting_inspection_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public_lighting_not_in_target',
            name='diimg',
        ),
        migrations.AddField(
            model_name='public_lighting_not_in_target',
            name='meter_readable',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('yes', 'YES'), ('no', 'NO')], max_length=50, null=True, verbose_name='Meter Readable'),
        ),
        migrations.AddField(
            model_name='public_lighting_not_in_target',
            name='meter_type',
            field=models.CharField(blank=True, choices=[('', '----CHOOSE A METER TYPE----'), ('nonsmart', 'NON SMART'), ('smart', 'SMART')], max_length=50, null=True, verbose_name='Meter Installation Type'),
        ),
        migrations.AddField(
            model_name='public_lighting_not_in_target',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_public_lighting_notinTarget', to='main.region'),
        ),
        migrations.AlterField(
            model_name='public_lighting_not_in_target',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_public_lighting_notintarget', to='main.county'),
        ),
    ]
