# Generated by Django 5.0.7 on 2025-03-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0038_remove_public_lighting_not_in_target_diimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_lighting_inspection',
            name='meterno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meter Number'),
        ),
    ]
