# Generated by Django 5.0.7 on 2025-03-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_region_publiclighting_daily_target_and_more'),
        ('postpaid', '0039_alter_public_lighting_inspection_meterno'),
        ('user', '0002_alter_userprofile_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_lighting_inspection',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_public_lighting_24', to='main.county'),
        ),
        migrations.AlterField(
            model_name='public_lighting_inspection',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_lighting_24', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='public_lighting_inspection',
            name='meteringstatus',
            field=models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('okay', 'OKAY'), ('faulty', 'FAULTY'), ('tampered', 'TAMPERED'), ('bypassed', 'BYPASSED')], max_length=50, verbose_name='Metering Status'),
        ),
        migrations.AlterField(
            model_name='public_lighting_inspection',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_public_lighting_24', to='main.region'),
        ),
        migrations.AlterField(
            model_name='public_lighting_inspection',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publiclighting_target_24', to='postpaid.public_lighting_target'),
        ),
        migrations.CreateModel(
            name='Public_lighting_inspection_25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meter Number')),
                ('accountno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number')),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('meter_type', models.CharField(blank=True, choices=[('', '----CHOOSE A METER TYPE----'), ('nonsmart', 'NON SMART'), ('smart', 'SMART')], max_length=50, null=True, verbose_name='Meter Installation Type')),
                ('phase', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('single', 'SINGLE PHASE'), ('threephase', 'THREE PHASE')], max_length=50, null=True, verbose_name='Phase Status')),
                ('meteringstatus', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('okay', 'OKAY'), ('faulty', 'FAULTY'), ('tampered', 'TAMPERED'), ('bypassed', 'BYPASSED')], max_length=50, verbose_name='Metering Status')),
                ('installationstatus', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('okay', 'OKAY'), ('notokay', 'NOT OKAY')], max_length=50, verbose_name='Installation Status')),
                ('faultystatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('blankscreen', 'BLANK SCREEN'), ('noncommunicating', 'NON COMMUNICATING'), ('obsolete', 'OBSOLETE'), ('fadeddigits', 'FADED DIGITS'), ('notpulsing', 'NOT PULSING'), ('burnt', 'BURNT'), ('batterylow', 'BATTERY LOW'), ('cuifaulty', 'CIU FAULTY'), ('notabletoloadtoken', 'NOT ABLE TO LOAD TOKEN'), ('looseglass', 'LOOSE GLASS')], default='NULL', max_length=50, null=True, verbose_name='Faulty Status')),
                ('tamperedstatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('brokenseaals', 'BROKEN SEALS'), ('disabledvoltage', 'DISABLED VOLTAGE'), ('disabledcurrent', 'DISABLED CURRENT'), ('brokenglass', 'BROKEN GLASS'), ('droppedlink', 'DROPPED LINK'), ('damagedmeter', 'DAMAGED METER'), ('foreignobjects', 'FOREIGN OBJECTS INTRODUCED')], max_length=50, null=True, verbose_name='Tampered Status')),
                ('bypassstatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('puncturedcable', 'PUNCTURED CABLE'), ('drilledcutout', 'DRILLED CUTOUT')], max_length=50, null=True, verbose_name='Bypass Status')),
                ('notokaystatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('loosejoints', 'LOOSE JOINTS'), ('noearth', 'NO EARTH'), ('demolishedpremises', 'DEMOLISHED PREMISES'), ('vacant', 'VACANT'), ('nometertails', 'NO METER TAILS'), ('loosemeterbox', 'LOOSE METERBOX')], max_length=50, null=True, verbose_name='Not Okay Status')),
                ('meter_readable', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('yes', 'YES'), ('no', 'NO')], max_length=50, null=True, verbose_name='Meter Readable')),
                ('reading', models.IntegerField(blank=True, help_text='Required', null=True, verbose_name='Meter Reading(This is a required Field)')),
                ('public_l_img', models.ImageField(upload_to='images/publicl/%Y/%m/%d/', verbose_name='CLEAR IMAGE UPLOAD(This is Required)')),
                ('diimg', models.ImageField(default='default.jpg', upload_to='di/publicl/%Y/%m/%d/', verbose_name='DI UPLOAD(Take a clear Picture of the DI Filled Form)')),
                ('metertype', models.CharField(blank=True, choices=[('', '----CHOOSE A METER TYPE----'), ('prepaid', 'PREPAID'), ('postpaid', 'POSTPAID')], max_length=50, null=True, verbose_name='Type Of Meter')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Any Comment')),
                ('y', models.CharField(max_length=255, verbose_name='Y')),
                ('x', models.CharField(max_length=255, verbose_name='X')),
                ('incms', models.BooleanField(default=False, verbose_name='Back Office Resolve')),
                ('nextlevel', models.BooleanField(default=False, verbose_name='Back Office Level')),
                ('billed', models.BigIntegerField(default=0, verbose_name='Rebilled Amount')),
                ('system_reading', models.IntegerField(blank=True, null=True, verbose_name='System Reading')),
                ('consumption', models.IntegerField(blank=True, null=True, verbose_name='Usage')),
                ('units', models.IntegerField(blank=True, null=True, verbose_name='Units')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_public_lighting', to='main.county')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_lighting', to='user.userprofile')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_public_lighting', to='main.region')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publiclighting_target', to='postpaid.public_lighting_target')),
            ],
        ),
    ]
