# Generated by Django 5.0.7 on 2025-03-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0040_alter_public_lighting_inspection_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_lighting_target',
            name='contract_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_lighting_target',
            name='tarrif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
