# Generated by Django 5.0.7 on 2025-04-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postpaid', '0042_lpodk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpodk',
            name='solar_installation_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
