# Generated by Django 5.0.7 on 2025-05-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_region_publiclighting_daily_target_and_more'),
        ('postpaid', '0043_alter_lpodk_solar_installation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpodk',
            name='county_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odk_county', to='main.county'),
        ),
        migrations.AlterField(
            model_name='lpodk',
            name='overall_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lpodk',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odk_region', to='main.region'),
        ),
    ]
