# Generated by Django 5.0.7 on 2025-12-19 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feeder_sections_aprx_length'),
        ('postpaid', '0045_lp_inspection_2025_2026'),
        ('user', '0002_alter_userprofile_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lp_inspection_2025_2026',
            name='county_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.county'),
        ),
        migrations.AlterField(
            model_name='lp_inspection_2025_2026',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region'),
        ),
        migrations.AlterField(
            model_name='lp_inspection_2025_2026',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile'),
        ),
        migrations.CreateModel(
            name='Amcorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('conn_config', models.CharField(choices=[('', '----CHOOSE A TYPE----'), ('3P3W', '3P3W'), ('3P4W', '3P4W')], max_length=10, verbose_name='Meter Configuration')),
                ('ct_ratio', models.CharField(choices=[('', '----CHOOSE CT----'), ('1:1A', '1:1A'), ('200/5A', '200/5A'), ('300/5A', '300/5A'), ('500/5A', '500/5A'), ('1000/5A', '1000/5A'), ('1500/5A', '1500/5A'), ('2000/5A', '2000/5A'), ('100/1A', '100/1A'), ('100/5A', '100/5A'), ('200/1A', '200/1A'), ('300/1A', '300/1A'), ('400/1A', '400/1A'), ('600/1A', '600/1A'), ('120/5A', '120/5A'), ('1200/5A', '1200/5A'), ('150/1A', '150/1A'), ('150/5A', '150/5A'), ('25/1A', '25/1A'), ('250/5A', '250/5A'), ('30/1A', '30/1A'), ('360/1A', '360/1A'), ('40/5A', '40/5A'), ('400/5A', '400/5A'), ('50/1A', '50/1A'), ('50/5A', '50/5A'), ('800/1A', '800/1A'), ('800/5A', '800/5A'), ('none', 'N/A')], max_length=50, verbose_name='CT Ratio')),
                ('vt_ratio', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('1:1V', '1:1V'), ('11,000/110V', '11,000/110V'), ('33,000/110V', '33,000/110V'), ('66,000/110V', '66,000/110V'), ('132,000/110V', '132,000/110V'), ('220,000/110V', '220,000/110V')], max_length=50, verbose_name='VT Ratio')),
                ('ct_programing', models.CharField(choices=[('', '----CHOOSE CT----'), ('1:1A', '1:1A'), ('200/5A', '200/5A'), ('300/5A', '300/5A'), ('500/5A', '500/5A'), ('1000/5A', '1000/5A'), ('1500/5A', '1500/5A'), ('2000/5A', '2000/5A'), ('100/1A', '100/1A'), ('100/5A', '100/5A'), ('200/1A', '200/1A'), ('300/1A', '300/1A'), ('400/1A', '400/1A'), ('600/1A', '600/1A'), ('120/5A', '120/5A'), ('1200/5A', '1200/5A'), ('150/1A', '150/1A'), ('150/5A', '150/5A'), ('25/1A', '25/1A'), ('250/5A', '250/5A'), ('30/1A', '30/1A'), ('360/1A', '360/1A'), ('40/5A', '40/5A'), ('400/5A', '400/5A'), ('50/1A', '50/1A'), ('50/5A', '50/5A'), ('800/1A', '800/1A'), ('800/5A', '800/5A'), ('none', 'N/A')], max_length=50, verbose_name='CT Programming')),
                ('vt_programing', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('1:1V', '1:1V'), ('11,000/110V', '11,000/110V'), ('33,000/110V', '33,000/110V'), ('66,000/110V', '66,000/110V'), ('132,000/110V', '132,000/110V'), ('220,000/110V', '220,000/110V')], max_length=50, verbose_name='VT Programming')),
                ('logger_red_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('logger_yellow_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('logger_blue_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('time_installed', models.TimeField(blank=True, null=True)),
                ('date_installed', models.DateField(blank=True, null=True)),
                ('instal_point', models.CharField(choices=[('', '----CHOOSE A TYPE----'), ('FEEDER', 'FEEDER'), ('TX', 'TX'), ('CUSTOMER_POINT', 'CUSTOMER POINT'), ('OTHER', 'OTHER')], max_length=50, verbose_name='Installation Point')),
                ('log_interval', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('read_180', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('read_181', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('read_182', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('feeder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('feeder_meter_number', models.CharField(blank=True, max_length=100, null=True)),
                ('feeder_voltage', models.CharField(choices=[('', '----CHOOSE A TYPE----'), ('11KV', '11KV'), ('33KV', '33KV'), ('66KV', '66KV')], max_length=50, verbose_name='Feeder Voltage')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amcorder_county', to='main.county')),
                ('meter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='postpaid.largepower_accounts_2024')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amcorder_region', to='main.region')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile')),
            ],
            options={
                'verbose_name': 'Amcorder Inspection',
                'verbose_name_plural': 'Amcorder Inspections',
                'indexes': [models.Index(fields=['meter'], name='postpaid_am_meter_i_54833d_idx')],
            },
        ),
    ]
