# Generated by Django 5.0.6 on 2024-05-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tid_meters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterno', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Meter Number')),
                ('accountno', models.CharField(max_length=20, verbose_name='Account Number')),
                ('itin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Itinerary')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector')),
                ('zone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Name')),
                ('mobile_vend', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Number')),
                ('mobile_incms', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Number')),
                ('tech_center', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tech Center')),
                ('office_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Office Name')),
                ('supply_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supply Address')),
                ('longitute', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('status', models.BooleanField(default=False)),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tid_county_target', to='main.county')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tid_region_target', to='main.region')),
            ],
        ),
        migrations.CreateModel(
            name='Tid_inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterno', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Meter Number')),
                ('accountno', models.CharField(max_length=20, verbose_name='Account Number')),
                ('dtadd', models.DateTimeField(auto_now_add=True)),
                ('dtupdate', models.DateTimeField(auto_now=True)),
                ('meteringstatus', models.CharField(choices=[('', '----CHOOSE A STATUS----'), ('okay', 'OKAY'), ('faulty', 'FAULTY'), ('tampered', 'TAMPERED'), ('bypassed', 'BYPASSED'), ('nometer', 'NO METER')], max_length=50, verbose_name='Metering Status')),
                ('faultystatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('blankscreen', 'BLANK SCREEN'), ('noncommunicating', 'NON COMMUNICATING'), ('obsolete', 'OBSOLETE'), ('fadeddigits', 'FADED DIGITS'), ('notpulsing', 'NOT PULSING'), ('burnt', 'BURNT'), ('batterylow', 'BATTERY LOW'), ('cuifaulty', 'CIU FAULTY'), ('notabletoloadtoken', 'NOT ABLE TO LOAD TOKEN'), ('looseglass', 'LOOSE GLASS')], default='NULL', max_length=50, null=True, verbose_name='Faulty Status')),
                ('tamperedstatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('brokenseaals', 'BROKEN SEALS'), ('disabledvoltage', 'DISABLED VOLTAGE'), ('disabledcurrent', 'DISABLED CURRENT'), ('brokenglass', 'BROKEN GLASS'), ('droppedlink', 'DROPPED LINK'), ('damagedmeter', 'DAMAGED METER'), ('foreignobjects', 'FOREIGN OBJECTS INTRODUCED')], max_length=50, null=True, verbose_name='Tampered Status')),
                ('bypassstatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('puncturedcable', 'PUNCTURED CABLE'), ('drilledcutout', 'DRILLED CUTOUT')], max_length=50, null=True, verbose_name='Bypass Status')),
                ('notokaystatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('loosejoints', 'LOOSE JOINTS'), ('noearth', 'NO EARTH'), ('demolishedpremises', 'DEMOLISHED PREMISES'), ('vacant', 'VACANT'), ('nometertails', 'NO METER TAILS'), ('loosemeterbox', 'LOOSE METERBOX')], max_length=50, null=True, verbose_name='Not Okay Status')),
                ('meterimg', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/tid/%Y/%m/%d/')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Any Comment')),
                ('sealno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Seal Number')),
                ('incms_status', models.BooleanField(default=False)),
                ('incms_nextlevel', models.BooleanField(default=False)),
                ('r_units', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Billed Units')),
                ('anomaly_status', models.BooleanField(default=False)),
                ('y', models.CharField(max_length=255, verbose_name='Y')),
                ('x', models.CharField(max_length=255, verbose_name='X')),
                ('tidstatus', models.CharField(blank=True, choices=[('', '----CHOOSE A STATUS----'), ('upgraded', 'UPGRADED'), ('failed', 'FAILED')], max_length=50, null=True, verbose_name='TID Status')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tid_county', to='main.county')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tid_inspector', to='user.userprofile')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tid_region', to='main.region')),
                ('tid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dc_target', to='prepaid.tid_meters')),
            ],
        ),
    ]
